name: Unit Tests

on: [push, pull_request]

jobs:
  unit_test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install Numpy
        run: pip install numpy

      - name: Run unit test for Problem 1
        run: |
          cd ./Precourse2/Problem1
          python dijkstra.py > output.txt
          diff output.txt answer.txt
          if [[ "$?" -eq "1" ]]; then exit 1 ; fi

      - name: Run unit test for Problem 2
        run: |
          cd ./Precourse2/Problem2
          python main.py input.txt
          diff output.txt answer.txt
          if [[ "$?" -eq "1" ]]; then exit 1 ; fi
          python main.py input_hard.txt
          diff output.txt answer_hard.txt
          if [[ "$?" -eq "1" ]]; then exit 1 ; fi

      - name: Run unit test for Problem 3
        run: |
          cd ./Precourse2/Problem3
          bash unit_test.sh
          if [[ "$?" -eq "1" ]]; then exit 1 ; fi
