name: Unit Tests Precourse 3

on: [push, pull_request]

jobs:
  unit_test:
    name: Run unit tests precourse 3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install Numpy
        run: pip install numpy

      - name: Install Pybind11
        run: pip install pybind11

      - name: Install C++ Compiler
        run: |
          sudo apt-get update && sudo apt-get install g++ -y
          sudo apt-get install mpich

      - name: Run unit test for Problem 1
        run: |
          cd ./Precourse3/Problem1/list
          make run
          if [[ "$?" -eq "1" ]]; then exit 1 ; fi
          cd ./Precourse3/Problem1/vector
          make run
          if [[ "$?" -eq "1" ]]; then exit 1 ; fi

      - name: Run unit test for Problem 2
        run: |
          cd ./Precourse3/Problem2
          gcc main.cpp -lstdc++ -o main
          ./main
          if [[ "$?" -eq "1" ]]; then exit 1 ; fi

      - name: Run unit test for Problem 3
        run: |
          cd ./Precourse3/Problem3
          g++ -O3 -Wall -shared -std=c++11 -fPIC $(python -m pybind11 --includes) matmul.cpp -o matmul_c$(python-config --extension-suffix)
          python main.py
          if [[ "$?" -eq "1" ]]; then exit 1 ; fi
